Switch to Logback
skylite-network/minestom-java pull request #1
Opened 2024-04-28 09:43 UTC by zax71

Replaces sfl4j with Logback configured to colourise logs

2024-04-28 18:01 UTC, mudkipdev requested changes

2024-04-28 18:01 UTC, mudkipdev commented on build.gradle.kts
> +    implementation("ch.qos.logback:logback-classic:1.4.14")
Latest version of logback-classic is 1.5.6

2024-04-28 18:01 UTC, mudkipdev commented on src/main/java/org/example/server/LogbackHighlightConfig.java
> +public class LogbackHighlightConfig extends ForegroundCompositeConverterBase<ILoggingEvent> {
Make this class final

2024-04-28 18:01 UTC, mudkipdev commented on src/main/resources/logback.xml
> +            <pattern>%d{HH:mm:ss} %highlightex([%level]): %highlightex(%msg%n)</pattern>
Time format should be `h:mm:ss a` to match what it was before (I use 24 hour time myself but I assumed there would be more people wanting 12 hour time)

2024-04-29 18:12 UTC, zax71 commented on src/main/java/org/example/server/LogbackHighlightConfig.java
> +public class LogbackHighlightConfig extends ForegroundCompositeConverterBase<ILoggingEvent> {
I never knew you could have final classes xD Tine to do some googling

2024-04-29 18:20 UTC, merged